version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo.2020
    ports:
      - 27017:27017
    volumes:
      - /home/mongo/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network
  schedule:
    image: schedule
    restart: always
    build: ../
    working_dir: /schedule
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ../:/schedule
      - ~/.m2:/root/.m2
    ports:
      - "8082:8082"
    command: mvn clean spring-boot:run
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
networks: 
    mongo-compose-network:
      driver: bridge